### DISCUSSION TITLE
Yaml vs JSON for data

### DISCUSSION THREAD

**Discussion by brittonhayes** [brittonhayes/warhammer-aos#26] [Ideas]
## Description

Instead of writing data configurations as JSON, it could be easier to work with as YAML. The API would still respond with JSON, but this could help to simplify the repo maintenance and editing.

### YAML

- Less verbose
- A bit easier to edit
- Can still be converted to JSON 
- No reliable means of performing schema validation.
- Could potentially still have to render out JSON file in the end from YAML data, which is a bit duplicative

```yaml
- army: "Daughters of Khaine"
  units:
    - name: "Avatar of Khaine"
      size: "40 mm"
      move: "2"
      save: "3"
      bravery: "4"
      wounds: "5"
      missile_weapon:
        - name: ""
          range: ""
          attacks: ""
          to_hit: ""
          to_wound: ""
          rend: ""
          damage: ""
      melee_weapon:
        - name: ""
          range: ""
          attacks: ""
          to_hit: ""
          to_wound: ""
          rend: ""
          damage: ""
      abilities:
        - name: ""
          desc: ""
      keywords:
        - ""
        - ""
```

### JSON

- Harder to edit
- Very strong schema validation available
- Very verbose so a little harder on the eyes

```json
 "army": "Daughters of Khaine",
  "units": [
    {
      "name": "Avatar of Khaine",
      "size": "40 mm",
      "move": "",
      "save": "",
      "bravery": "",
      "wounds": "",
      "missile_weapon": [
        {
          "name": "",
          "range": "",
          "attacks": "",
          "to_hit": "",
          "to_wound": "",
          "rend": "",
          "damage": ""
        }
      ],
      "melee_weapon": [
        {
          "name": "",
          "range": "",
          "attacks": "",
          "to_hit": "",
          "to_wound": "",
          "rend": "",
          "damage": ""
        }
      ],
      "abilities": [
        {
          "name": "",
          "desc": ""
        },
        {
          "name": "",
          "desc": ""
        }
      ],
      "keywords": [
        ""
      ]
    },
]
```

### JSON from YAML

While this is a bit duplicative, worth mentioning that we could absolutely generate JSON blobs from the YAML using Go text/template

```gotemplate
[{{ range .armies}}
    {
        "army": "{{.name}}",
        "units": {{- range .units}} {
            "name": {{.name}},
            "size": {{.size}},
            "move": {{.move}},
            "save": {{.save}},
            "bravery": {{.bravery}}
            "wounds":{{.wounds}}
        },{{end}}
    },
{{end}}]
```

## Validation 

- [Yamale](https://github.com/23andMe/Yamale) is an option for YAML schema validation.

- [AJV](https://github.com/ajv-validator/ajv-cli) is what we're currently using to validate the JSON.
